### ISSUE TITLE
 geoJsonFlatten is not a function error

### ISSUE THREAD

**Issue by stigmergic** [mapbox/geojson-extent#14]
In a react app we grab the bounds of a geojson using this lib:

import * as getExtent from '@mapbox/geojson-extent'
...
            this.bounds = getExtent(this.json)
...

This works fine in 0.3.2 but breaks in 1.0.0 with an error: "geojsonFlatten is not a function". In the extent() function in geojson-coords.

**Comment by BAByrne** [comment]
I'm noticing this in v0.4.0 as well.

**Comment by tayden** [comment]
Any plans to fix this?

**Comment by tayden** [comment]
I looked into this a bit. It looks like the `geojson-flatten` lib which is a dependency of `@mapbox/geojson-flatten` is now exporting a Module, rather than a function.

If you change this line in `@mapbox/geojsonFlatten/index.js` from 

```
var normalized = geojsonFlatten(geojsonNormalize(_))
```

 to
 ```
 var normalized = geojsonFlatten.default(geojsonNormalize(_))
 ```
 
 things work as expected

**Comment by tayden** [comment]
Should be fixed by https://github.com/mapbox/geojson-coords/pull/2 if someone can merge that...

**Comment by saeedezzati** [comment]
Can someone please merge this fix!?!?

**Comment by zbycz** [comment]
Still occurs in @mapbox/geojson-extent 1.0.0

I replaced the package with my own utility function:
```
const getBbox = (coordinates) => {
  const [firstX, firstY] = coordinates[0];
  const initialBbox = { w: firstX, s: firstY, e: firstX, n: firstY };

  return coordinates.reduce(
    ({ w, s, e, n }, [x, y]) => ({
      w: Math.min(w, x),
      s: Math.min(s, y),
      e: Math.max(e, x),
      n: Math.max(n, y),
    }),
    initialBbox,
  );
};
```

**Comment by bbusch19** [comment]
Any update on when this might be fixed?
